<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $reportInfo['label'] }} - PDF Export</title>
    <style>
        @page {
            margin: 15mm 15mm 15mm 15mm;
        }
        body {
            font-family: 'Helvetica', 'Segoe UI', Arial, sans-serif;
            font-size: 10px;
            color: #1e293b;
            background-color: #ffffff;
            margin: 0;
            padding: 0;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 16px;
            border-bottom: 3px solid #d4af37;
            padding-bottom: 12px;
        }
        .header-logo {
            max-height: 40px;
            width: auto;
        }
        .company-title {
            font-size: 20px;
            font-weight: bold;
            color: #004225;
            letter-spacing: 0.5px;
        }
        .report-title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            margin-top: 2px;
        }
        .metadata-box {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-left: 4px solid #004225;
            border-radius: 6px;
            padding: 10px 14px;
            margin-bottom: 16px;
            font-size: 9.5px;
        }
        .metadata-grid {
            width: 100%;
            border-collapse: collapse;
        }
        .metadata-grid td {
            padding: 3px 6px;
            vertical-align: top;
        }
        .meta-label {
            font-weight: bold;
            color: #64748b;
            text-transform: uppercase;
            font-size: 8.5px;
        }
        .meta-value {
            font-weight: bold;
            color: #0f172a;
        }
        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            font-size: 9px;
        }
        .report-table th {
            background-color: #004225;
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 8px 6px;
            border: 1px solid #00331c;
            text-transform: uppercase;
            font-size: 8.5px;
            letter-spacing: 0.3px;
        }
        .report-table td {
            padding: 6px 6px;
            border: 1px solid #e2e8f0;
            vertical-align: top;
            word-wrap: break-word;
        }
        .report-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-success { background-color: #dcfce7; color: #15803d; }
        .badge-warning { background-color: #fef3c7; color: #92400e; }
        .badge-info { background-color: #e0f2fe; color: #0369a1; }
        .badge-danger { background-color: #fee2e2; color: #b91c1c; }
        .footer-text {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding-top: 6px;
        }
        .empty-state {
            text-align: center;
            padding: 30px;
            color: #64748b;
            font-style: italic;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <table class="header-table">
        <tr>
            <td style="vertical-align: middle;">
                @if (!empty($logoUrl))
                    <img src="{{ $logoUrl }}" class="header-logo" alt="Logo">
                @endif
                <div class="company-title">{{ $companyName }}</div>
                <div class="report-title">{{ $reportInfo['label'] }}</div>
            </td>
            <td style="text-align: right; vertical-align: bottom;">
                <div style="font-size: 11px; font-weight: bold; color: #004225;">OFFICIAL SYSTEM REPORT</div>
                <div style="font-size: 9px; color: #64748b;">Generated: {{ $generatedAt }}</div>
                <div style="font-size: 9px; color: #64748b;">Generated By: {{ $generatedBy }}</div>
            </td>
        </tr>
    </table>

    <!-- Metadata & Active Filters -->
    <div class="metadata-box">
        <table class="metadata-grid">
            <tr>
                <td style="width: 25%;">
                    <span class="meta-label">Report Category:</span><br>
                    <span class="meta-value">{{ $reportInfo['category'] ?? 'General' }}</span>
                </td>
                <td style="width: 25%;">
                    <span class="meta-label">Date Range Filter:</span><br>
                    <span class="meta-value">
                        @if(!empty($filters['date_from']) || !empty($filters['date_to']))
                            {{ $filters['date_from'] ?? 'Earliest' }} to {{ $filters['date_to'] ?? 'Today' }}
                        @else
                            All Time
                        @endif
                    </span>
                </td>
                <td style="width: 25%;">
                    <span class="meta-label">Status Filter:</span><br>
                    <span class="meta-value">{{ !empty($filters['status']) ? $filters['status'] : 'All Statuses' }}</span>
                </td>
                <td style="width: 25%;">
                    <span class="meta-label">Total Matching Records:</span><br>
                    <span class="meta-value" style="color: #004225; font-size: 11px;">{{ number_format($totalRecords) }}</span>
                </td>
            </tr>
            @if(!empty($filters['search']) || !empty($filters['service_id']) || !empty($filters['country']))
            <tr>
                <td colspan="4" style="padding-top: 4px;">
                    <span class="meta-label">Active Additional Filters:</span>
                    <span class="meta-value">
                        @if(!empty($filters['search'])) Search: "{{ $filters['search'] }}" &nbsp;|&nbsp; @endif
                        @if(!empty($filters['country'])) Country: {{ $filters['country'] }} &nbsp;|&nbsp; @endif
                        @if(!empty($filters['payment_status'])) Payment Status: {{ $filters['payment_status'] }} @endif
                    </span>
                </td>
            </tr>
            @endif
        </table>
    </div>

    <!-- Data Table -->
    @if(count($records) > 0)
        <table class="report-table">
            <thead>
                <tr>
                    <th style="width: 30px;">#</th>
                    @foreach($columns as $col)
                        <th>{{ $col }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($records as $idx => $rec)
                    @php
                        $row = \App\Services\ReportExportService::formatRecordRow($reportType, $rec);
                    @endphp
                    <tr>
                        <td style="text-align: center; font-weight: bold; color: #64748b;">{{ $idx + 1 }}</td>
                        @foreach($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty-state">
            No system records found matching the specified report criteria.
        </div>
    @endif

    <!-- Footer -->
    <div class="footer-text">
        Confidential Document &bull; Generated from {{ $companyName }} Reporting System &bull; Page 1
    </div>
</body>
</html>
